version: "3"

services:
  dk-full-back:
    container_name: dk-full-back
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5676:5676

  dk-full-front:
    container_name: dk-full-front
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - /app/frontend/node_modules
